# Generated by Django 5.1.2 on 2024-11-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0003_alter_emailconfirmation_confirmation_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailConfirmation',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='email',
        ),
    ]
