# Generated by Django 5.1.2 on 2024-12-01 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=20)),
                ('goal_amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('savings', models.DecimalField(decimal_places=0, max_digits=10)),
                ('status', models.CharField(default='in progress', max_length=50)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='cashflow.child')),
            ],
        ),
    ]
