# Generated by Django 5.1.2 on 2024-12-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0002_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='cate_choices',
            field=models.CharField(choices=[('needs', 'نیازها'), ('wants', 'خواسته ها'), ('else', 'سایر'), ('parent', 'والدین'), ('part_time_job', 'کار نیمه\u200cوقت'), ('other', 'دیگر')], default='needs', max_length=20),
        ),
    ]
