# Generated by Django 5.1.2 on 2024-12-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0003_alter_cost_cate_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='cate_choices',
            field=models.CharField(choices=[('needs', 'نیازها'), ('wants', 'خواسته ها'), ('other', 'سایر'), ('parent', 'والدین'), ('part_time_job', 'کار نیمه\u200cوقت'), ('other', 'دیگر')], default='needs', max_length=20),
        ),
        migrations.AlterField(
            model_name='goals',
            name='status',
            field=models.CharField(choices=[('جاری', 'جاری'), ('کامل', 'کامل')], default='جاری', max_length=20),
        ),
    ]
