# Generated by Django 5.1.2 on 2024-11-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0005_alter_cost_cate_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='cate_choices',
            field=models.CharField(choices=[('food', 'خوراکی'), ('needs', 'موارد ضروری'), ('education', 'آموزش'), ('health_cosmetics', 'مواد بهداشتی و آرایشی'), ('clothes', 'لباس'), ('else', 'سایر'), ('parent', 'والدین'), ('part_time_job', 'کار نیمه\u200cوقت'), ('other', 'دیگر')], default='food', max_length=20),
        ),
    ]
